export type TrackKey = "reviewer" | "ai-service" | "affiliate" | "seo-blog" | "ecommerce";

export type CategoryGroup = {
  key: TrackKey;
  title: string;
  description: string;
  categories: string[];
};

export type Course = {
  slug: string;
  title: string;
  category: string;
  group: TrackKey;
  summary: string;
  target: string;
  level: "입문" | "기초" | "실전";
  duration: string;
  minutes: number;
  price: string;
  priceNumber: number;
  tags: string[];
  thumbnail: string;
  heroImage?: string;
  materialPdf: string;
  badge: string;
  cardCategory: string;
  originalPrice: string;
  rating: number;
  reviewCount: number;
  intro: string;
  recommendedFor: string[];
  learnings: string[];
  curriculum: string[];
  formats: string[];
  outcomes: string[];
  caution: string;
  relatedSlugs: string[];
};

export const categoryGroups: CategoryGroup[] = [
  {
    key: "reviewer",
    title: "리뷰어",
    description: "체험단과 리뷰 콘텐츠로 작게 시작하는 실행형 부업 구조를 이해합니다.",
    categories: ["체험단 입문", "블로그 리뷰", "SNS 리뷰 콘텐츠"],
  },
  {
    key: "ai-service",
    title: "AI 활용기반 서비스 제작",
    description: "AI 도구로 콘텐츠와 작은 서비스를 만들어 수익으로 연결하는 흐름을 배웁니다.",
    categories: ["AI 콘텐츠 제작", "AI 자동화", "AI 디지털 상품"],
  },
  {
    key: "affiliate",
    title: "제휴 마케팅",
    description: "추천 링크와 콘텐츠로 전환을 만드는 제휴 수익 구조를 살펴봅니다.",
    categories: ["제휴 마케팅 입문", "쿠팡 파트너스", "SNS 링크 수익"],
  },
  {
    key: "seo-blog",
    title: "SEO & 블로그 수익화",
    description: "검색 유입을 만드는 글쓰기와 블로그 수익화 구조를 정리합니다.",
    categories: ["블로그 수익화", "검색 SEO", "애드센스"],
  },
  {
    key: "ecommerce",
    title: "이커머스",
    description: "상품 소싱, 판매, 운영 흐름을 중심으로 온라인 판매 구조를 배웁니다.",
    categories: ["이커머스 입문", "위탁판매", "상품 소싱"],
  },
];

export const courses: Course[] = [
  {
    slug: "reviewer-program",
    title: "리뷰어 / 체험단 구조 이해",
    category: "체험단 입문",
    group: "reviewer",
    summary: "체험단, 협찬, 리뷰 콘텐츠가 어떤 조건에서 운영되는지 알아봅니다.",
    target: "작게 시작 가능한 실행형 활동이 궁금한 분",
    level: "입문",
    duration: "30분",
    minutes: 30,
    price: "12,000원",
    priceNumber: 12000,
    tags: ["입문자용", "가벼운 시작", "실행형"],
    thumbnail: "/course-thumbnails/reviewer-program.webp",
    materialPdf: "/course-materials/reviewer-program.pdf",
    badge: "입문추천",
    cardCategory: "체험단",
    originalPrice: "29,000원",
    rating: 4.7,
    reviewCount: 721,
    intro: "리뷰어와 체험단 활동의 기본 조건, 콘텐츠 기준, 주의사항을 현실적으로 정리합니다.",
    recommendedFor: [
      "큰 초기 비용 없이 온라인 활동을 경험하고 싶은 분",
      "블로그나 SNS 계정 운영을 작게 시작하는 분",
      "체험단 활동의 구조와 기준이 궁금한 분",
    ],
    learnings: [
      "체험단과 협찬의 기본 구조",
      "선정 기준과 계정 준비 방법",
      "리뷰 콘텐츠 작성 시 유의할 점",
      "활동을 수익 모델로 확장하는 방향",
    ],
    curriculum: [
      "리뷰어 활동의 기본 흐름",
      "플랫폼별 신청 방식",
      "리뷰 작성 체크리스트",
      "장기적으로 확장 가능한 방향",
    ],
    formats: ["PDF 12p", "신청 체크리스트", "예시 이미지"],
    outcomes: [
      "체험단 활동이 어떤 조건으로 운영되는지 이해합니다.",
      "내 계정을 준비할 때 필요한 기본 요소를 확인할 수 있습니다.",
    ],
    caution: "제공받은 상품과 광고성 표시 기준을 명확히 지켜야 합니다. 무리한 후기 작성은 권장하지 않습니다.",
    relatedSlugs: ["blog-reviewer-start", "sns-review-content"],
  },
  {
    slug: "blog-reviewer-start",
    title: "블로그 리뷰어 첫 활동 가이드",
    category: "블로그 리뷰",
    group: "reviewer",
    summary: "블로그로 체험단·리뷰어 활동을 시작할 때 필요한 계정 준비와 글쓰기 기준을 정리합니다.",
    target: "블로그로 리뷰 활동을 시작하려는 분",
    level: "입문",
    duration: "35분",
    minutes: 35,
    price: "13,000원",
    priceNumber: 13000,
    tags: ["입문자용", "실행형", "블로그"],
    thumbnail: "/course-thumbnails/blog-monetization.webp",
    materialPdf: "/course-materials/reviewer-program.pdf",
    badge: "입문추천",
    cardCategory: "블로그 리뷰",
    originalPrice: "32,000원",
    rating: 4.6,
    reviewCount: 214,
    intro: "블로그를 활용해 체험단과 리뷰어 활동을 시작할 때 필요한 계정 준비, 신청 방법, 후기 작성 기준을 정리한 입문 강의입니다.",
    recommendedFor: [
      "블로그로 체험단 활동을 처음 시작하려는 분",
      "리뷰 글을 어떻게 써야 할지 막막한 분",
      "꾸준한 활동으로 계정을 키우고 싶은 분",
    ],
    learnings: [
      "체험단 신청에 필요한 블로그 준비",
      "선정 확률을 높이는 계정 운영법",
      "신뢰를 주는 리뷰 글쓰기 기준",
    ],
    curriculum: [
      "블로그 리뷰어 활동의 기본 흐름",
      "체험단 신청과 선정 기준",
      "리뷰 글 구성과 사진 배치",
      "광고 표시와 주의사항",
    ],
    formats: ["PDF 14p", "신청 체크리스트", "리뷰 글 예시"],
    outcomes: [
      "블로그 체험단 활동의 시작 절차를 이해합니다.",
      "리뷰 글의 기본 구성을 직접 잡을 수 있습니다.",
    ],
    caution: "체험단은 제공받은 제품과 광고성 표기를 명확히 해야 합니다. 선정과 수익에는 시간이 필요합니다.",
    relatedSlugs: ["reviewer-program", "sns-review-content"],
  },
  {
    slug: "sns-review-content",
    title: "SNS 리뷰 콘텐츠 만들기",
    category: "SNS 리뷰 콘텐츠",
    group: "reviewer",
    summary: "인스타그램 등 SNS에서 리뷰 콘텐츠를 만들고 협찬으로 연결하는 흐름을 살펴봅니다.",
    target: "SNS로 리뷰·협찬 활동을 해보고 싶은 분",
    level: "기초",
    duration: "40분",
    minutes: 40,
    price: "16,000원",
    priceNumber: 16000,
    tags: ["실행형", "SNS", "리뷰"],
    thumbnail: "/course-thumbnails/shorts-reels.webp",
    materialPdf: "/course-materials/reviewer-program.pdf",
    badge: "신규",
    cardCategory: "SNS 리뷰",
    originalPrice: "36,000원",
    rating: 4.7,
    reviewCount: 188,
    intro: "인스타그램 등 SNS에서 리뷰 콘텐츠를 만들고 협찬·체험단으로 연결하는 흐름을 사례 중심으로 살펴봅니다.",
    recommendedFor: [
      "SNS 계정으로 리뷰 활동을 해보고 싶은 분",
      "사진·짧은 영상 콘텐츠가 익숙한 분",
      "협찬 제안을 받는 계정을 만들고 싶은 분",
    ],
    learnings: [
      "SNS 리뷰 콘텐츠의 기본 포맷",
      "협찬으로 이어지는 계정 운영",
      "콘텐츠 신뢰도를 지키는 방법",
    ],
    curriculum: [
      "SNS 리뷰 활동의 수익 구조",
      "콘텐츠 포맷과 촬영 기본",
      "협찬 제안과 소통 방식",
      "표시 광고 가이드 준수",
    ],
    formats: ["PDF 14p", "콘텐츠 예시", "체크리스트"],
    outcomes: [
      "SNS 리뷰 콘텐츠의 기본 형태를 이해합니다.",
      "협찬으로 연결되는 계정 운영 방향을 잡을 수 있습니다.",
    ],
    caution: "협찬 콘텐츠는 광고 표시 기준을 반드시 지켜야 하며, 계정 신뢰가 장기적인 핵심입니다.",
    relatedSlugs: ["reviewer-program", "blog-reviewer-start"],
  },
  {
    slug: "instagram-reels-ai",
    title: "Instagram Reels로 AI 기반 부업 시작하기",
    category: "AI 콘텐츠 제작",
    group: "ai-service",
    summary: "AI 도구로 인스타그램 릴스를 기획·제작하고 수익으로 연결하는 흐름을 처음부터 배웁니다.",
    target: "릴스로 부업을 시작하고 싶은 완전 초보자",
    level: "입문",
    duration: "40분",
    minutes: 40,
    price: "무료",
    priceNumber: 0,
    tags: ["무료", "입문자용", "AI", "추천"],
    thumbnail: "/course-thumbnails/shorts-reels.webp",
    materialPdf: "https://www.image2url.com/r2/default/documents/1779359192971-054d2141-9d45-4efc-8591-062cf8c70a0a.pdf",
    badge: "무료",
    cardCategory: "AI 릴스",
    originalPrice: "39,000원",
    rating: 4.9,
    reviewCount: 312,
    intro: "촬영 장비나 편집 경험이 없어도 괜찮습니다. AI 도구를 활용해 인스타그램 릴스의 주제 선정부터 대본, 제작, 업로드까지 한 흐름으로 이해하고, 릴스가 어떻게 수익으로 이어지는지 정리하는 무료 입문 강의입니다.",
    recommendedFor: [
      "릴스를 만들어 본 적 없지만 부업으로 시작해보고 싶은 분",
      "AI 도구로 콘텐츠 제작 시간을 줄이고 싶은 분",
      "얼굴 노출 없이 시작할 수 있는 방법을 찾는 분",
    ],
    learnings: [
      "AI로 릴스 주제와 대본을 빠르게 만드는 방법",
      "무료 AI 도구로 영상·자막·음성을 제작하는 흐름",
      "릴스가 광고·제휴·협찬 수익으로 연결되는 구조",
      "초보자가 피해야 할 흔한 시행착오",
    ],
    curriculum: [
      "릴스 부업의 수익 구조 한눈에 보기",
      "AI로 주제 발굴하고 대본 작성하기",
      "AI 도구로 영상·자막 제작하기",
      "꾸준히 올리는 7일 업로드 루틴",
    ],
    formats: ["PDF 20p", "AI 도구 목록", "릴스 기획 템플릿"],
    outcomes: [
      "AI 도구를 활용해 릴스 한 편을 직접 완성할 수 있습니다.",
      "릴스가 어떤 방식으로 수익에 기여하는지 이해할 수 있습니다.",
    ],
    caution: "릴스는 반응 편차가 크고 성장에 시간이 필요합니다. 이 강의는 수익을 보장하지 않으며, 시작 전 구조 이해와 첫 실행을 돕는 자료입니다.",
    relatedSlugs: ["ai-service-builder", "ai-content-automation"],
  },
  {
    slug: "ai-service-builder",
    title: "AI 활용 기반 서비스 제작",
    category: "AI 디지털 상품",
    group: "ai-service",
    summary: "AI 도구로 작은 서비스나 자동화 산출물을 만들 때 필요한 흐름을 배웁니다.",
    target: "AI 툴로 실행형 부업을 탐색하는 분",
    level: "기초",
    duration: "50분",
    minutes: 50,
    price: "21,000원",
    priceNumber: 21000,
    tags: ["추천", "AI", "서비스형"],
    thumbnail: "/course-thumbnails/ai-service-builder.webp",
    materialPdf: "https://www.image2url.com/r2/default/documents/1779359192971-054d2141-9d45-4efc-8591-062cf8c70a0a.pdf",
    badge: "추천",
    cardCategory: "AI 서비스",
    originalPrice: "59,000원",
    rating: 4.8,
    reviewCount: 1234,
    intro: "AI 도구를 활용해 작은 문제를 해결하고 서비스형 산출물로 연결하는 흐름을 설명합니다.",
    recommendedFor: [
      "AI 툴은 써봤지만 수익화 방향이 막막한 분",
      "자동화, 문서, 콘텐츠 제작을 서비스로 만들고 싶은 분",
      "혼자 작게 테스트할 수 있는 모델을 찾는 분",
    ],
    learnings: [
      "AI 활용 부업의 대표 유형",
      "문제 정의와 산출물 설계 방식",
      "작은 서비스 제안서 구성",
      "품질 확인과 윤리적 안내 기준",
    ],
    curriculum: [
      "AI 서비스형 부업의 큰 그림",
      "도구보다 먼저 정할 문제",
      "산출물 패키징 예시",
      "첫 고객 검증 흐름",
    ],
    formats: ["PDF 20p", "서비스 기획 템플릿", "프로세스 도식"],
    outcomes: [
      "AI 도구를 단순 사용이 아니라 문제 해결 흐름으로 바라볼 수 있습니다.",
      "작은 서비스 제안의 기본 구조를 만들 수 있습니다.",
    ],
    caution: "AI 결과물은 검수와 책임 있는 사용이 중요합니다. 자동화만으로 품질이 보장되지는 않습니다.",
    relatedSlugs: ["instagram-reels-ai", "ai-content-automation"],
  },
  {
    slug: "ai-content-automation",
    title: "AI 콘텐츠 자동화 입문",
    category: "AI 자동화",
    group: "ai-service",
    summary: "AI 도구를 연결해 콘텐츠 제작 과정을 반복 가능한 작업 흐름으로 만드는 방법을 배웁니다.",
    target: "콘텐츠 제작 시간을 줄이고 싶은 분",
    level: "기초",
    duration: "45분",
    minutes: 45,
    price: "22,000원",
    priceNumber: 22000,
    tags: ["AI", "자동화", "효율"],
    thumbnail: "/course-thumbnails/ai-service-builder.webp",
    materialPdf: "/course-materials/ai-service-builder.pdf",
    badge: "추천",
    cardCategory: "AI 자동화",
    originalPrice: "52,000원",
    rating: 4.7,
    reviewCount: 263,
    intro: "여러 AI 도구를 하나의 작업 흐름으로 연결해, 콘텐츠 제작 시간을 줄이는 반복 가능한 자동화 구조를 배웁니다.",
    recommendedFor: [
      "콘텐츠 제작에 시간이 너무 많이 드는 분",
      "AI 도구를 효율적으로 묶어 쓰고 싶은 분",
      "반복 작업을 줄이고 싶은 1인 운영자",
    ],
    learnings: [
      "콘텐츠 제작 단계별 AI 도구 선택",
      "도구를 연결하는 작업 흐름 설계",
      "품질을 유지하는 검수 기준",
    ],
    curriculum: [
      "콘텐츠 자동화의 기본 개념",
      "기획·작성·편집 단계별 도구",
      "작업 흐름 템플릿 만들기",
      "검수와 품질 관리",
    ],
    formats: ["PDF 18p", "도구 비교표", "작업 흐름 템플릿"],
    outcomes: [
      "내 콘텐츠 작업을 단계로 나눠 자동화 지점을 찾을 수 있습니다.",
      "반복 가능한 제작 흐름을 설계할 수 있습니다.",
    ],
    caution: "자동화는 시간을 줄여 주지만 최종 검수는 필요합니다. 도구는 자주 바뀌므로 흐름 중심으로 익히는 것이 좋습니다.",
    relatedSlugs: ["instagram-reels-ai", "ai-service-builder"],
  },
  {
    slug: "affiliate-marketing",
    title: "제휴 마케팅 첫 구조 이해",
    category: "제휴 마케팅 입문",
    group: "affiliate",
    summary: "추천 링크, 콘텐츠, 전환율이 어떻게 수익으로 연결되는지 설명합니다.",
    target: "콘텐츠와 상품 연결에 관심 있는 분",
    level: "입문",
    duration: "40분",
    minutes: 40,
    price: "18,000원",
    priceNumber: 18000,
    tags: ["입문자용", "실전형", "마케팅형"],
    thumbnail: "/course-thumbnails/affiliate-marketing.webp",
    materialPdf: "/course-materials/affiliate-marketing.pdf",
    badge: "추천",
    cardCategory: "제휴",
    originalPrice: "49,000원",
    rating: 4.7,
    reviewCount: 987,
    intro: "제휴 마케팅을 과장 없이 이해할 수 있도록 링크 수익의 기본 흐름과 주의점을 정리합니다.",
    recommendedFor: [
      "링크를 통해 수익이 생기는 방식이 궁금한 분",
      "블로그, SNS, 숏폼을 수익화하고 싶은 분",
      "광고 느낌을 줄이고 신뢰를 지키는 기준이 필요한 분",
    ],
    learnings: [
      "제휴 링크와 전환 추적의 기본",
      "상품 선택과 콘텐츠 주제의 연결",
      "신뢰를 해치지 않는 추천 방식",
      "성과를 판단하는 기본 지표",
    ],
    curriculum: [
      "제휴 마케팅의 수익 흐름",
      "콘텐츠 채널별 적용 방식",
      "추천 글과 비교 글의 차이",
      "초보자가 지켜야 할 표시와 안내",
    ],
    formats: ["PDF 16p", "전환 흐름 도식", "체크리스트"],
    outcomes: [
      "제휴 마케팅을 시작하기 전 필요한 기본 용어를 이해합니다.",
      "내 채널에 맞는 상품 연결 방식을 판단할 수 있습니다.",
    ],
    caution: "제휴는 신뢰가 핵심입니다. 무리한 추천이나 과장 표현은 장기적으로 채널 가치를 낮출 수 있습니다.",
    relatedSlugs: ["coupang-partners", "sns-affiliate-link"],
  },
  {
    slug: "coupang-partners",
    title: "쿠팡 파트너스 시작하기",
    category: "쿠팡 파트너스",
    group: "affiliate",
    summary: "쿠팡 파트너스의 가입부터 링크 생성, 콘텐츠 연결까지 기본 흐름을 정리합니다.",
    target: "제휴 링크 수익을 처음 시작하는 분",
    level: "입문",
    duration: "35분",
    minutes: 35,
    price: "14,000원",
    priceNumber: 14000,
    tags: ["입문자용", "제휴", "실전형"],
    thumbnail: "/course-thumbnails/affiliate-marketing.webp",
    materialPdf: "/course-materials/affiliate-marketing.pdf",
    badge: "입문추천",
    cardCategory: "쿠팡 파트너스",
    originalPrice: "33,000원",
    rating: 4.6,
    reviewCount: 341,
    intro: "쿠팡 파트너스의 가입, 추천 링크 생성, 콘텐츠 연결까지 제휴 수익의 첫 흐름을 정리한 입문 강의입니다.",
    recommendedFor: [
      "제휴 링크 수익을 처음 시작하는 분",
      "블로그나 SNS에 추천 링크를 넣어보고 싶은 분",
      "작게 테스트하며 배우고 싶은 분",
    ],
    learnings: [
      "쿠팡 파트너스 가입과 기본 정책",
      "추천 링크 생성과 삽입 방법",
      "전환을 만드는 콘텐츠 연결",
    ],
    curriculum: [
      "쿠팡 파트너스 수익 구조",
      "가입과 링크 생성",
      "콘텐츠에 링크 연결하기",
      "표시 안내와 주의사항",
    ],
    formats: ["PDF 14p", "시작 체크리스트", "예시 이미지"],
    outcomes: [
      "쿠팡 파트너스의 기본 흐름을 이해합니다.",
      "내 콘텐츠에 추천 링크를 연결하는 방법을 알 수 있습니다.",
    ],
    caution: "제휴 링크는 광고임을 명확히 표시해야 합니다. 클릭과 전환에는 시간이 필요합니다.",
    relatedSlugs: ["affiliate-marketing", "sns-affiliate-link"],
  },
  {
    slug: "sns-affiliate-link",
    title: "SNS 링크로 제휴 수익 만들기",
    category: "SNS 링크 수익",
    group: "affiliate",
    summary: "SNS 프로필과 콘텐츠에 제휴 링크를 자연스럽게 연결해 전환을 만드는 방법을 배웁니다.",
    target: "SNS 계정을 제휴 수익으로 연결하고 싶은 분",
    level: "기초",
    duration: "40분",
    minutes: 40,
    price: "17,000원",
    priceNumber: 17000,
    tags: ["SNS", "제휴", "마케팅형"],
    thumbnail: "/course-thumbnails/agency-sidejob.webp",
    materialPdf: "/course-materials/affiliate-marketing.pdf",
    badge: "신규",
    cardCategory: "SNS 제휴",
    originalPrice: "39,000원",
    rating: 4.6,
    reviewCount: 226,
    intro: "SNS 프로필과 콘텐츠에 제휴 링크를 자연스럽게 배치해, 팔로워의 신뢰를 지키면서 전환을 만드는 방법을 배웁니다.",
    recommendedFor: [
      "운영 중인 SNS 계정을 수익화하고 싶은 분",
      "광고 느낌을 줄이고 싶은 분",
      "링크 기반 수익 구조가 궁금한 분",
    ],
    learnings: [
      "프로필·콘텐츠 링크 배치 전략",
      "신뢰를 지키는 추천 방식",
      "전환을 확인하는 기본 지표",
    ],
    curriculum: [
      "SNS 제휴 수익의 기본 구조",
      "프로필 링크와 콘텐츠 연결",
      "추천 콘텐츠 만드는 법",
      "성과 점검과 개선",
    ],
    formats: ["PDF 16p", "전환 흐름 도식", "체크리스트"],
    outcomes: [
      "SNS에서 제휴 링크가 작동하는 방식을 이해합니다.",
      "신뢰를 지키는 추천 콘텐츠 기준을 세울 수 있습니다.",
    ],
    caution: "과한 추천은 팔로워 신뢰를 떨어뜨립니다. 광고 표시를 지키고 꾸준히 검증하는 것이 중요합니다.",
    relatedSlugs: ["affiliate-marketing", "coupang-partners"],
  },
  {
    slug: "blog-monetization",
    title: "블로그 수익화 구조",
    category: "블로그 수익화",
    group: "seo-blog",
    summary: "네이버 블로그, 티스토리, 워드프레스의 수익화 차이를 한 번에 비교합니다.",
    target: "글쓰기에 익숙하거나 검색 유입을 배우고 싶은 분",
    level: "기초",
    duration: "55분",
    minutes: 55,
    price: "무료",
    priceNumber: 0,
    tags: ["무료", "검색형", "기초"],
    thumbnail: "/course-thumbnails/blog-monetization.webp",
    heroImage: "/course-hero/blog-monetization-hero.webp",
    materialPdf: "/course-materials/blog-monetization.pdf",
    badge: "무료",
    cardCategory: "블로그",
    originalPrice: "22,000원",
    rating: 4.8,
    reviewCount: 1822,
    intro: "블로그 플랫폼별 특징과 광고, 제휴, 체험단, 자체 상품 연결 방식을 비교합니다.",
    recommendedFor: [
      "블로그를 시작하려는데 플랫폼 선택이 어려운 분",
      "검색 유입이 수익으로 이어지는 과정을 알고 싶은 분",
      "글 기반 부업의 현실적인 장단점을 보고 싶은 분",
    ],
    learnings: [
      "플랫폼별 수익 모델 차이",
      "검색 키워드와 콘텐츠 기획의 연결",
      "광고, 체험단, 제휴 수익의 기본 구조",
      "초기 블로그 운영 체크리스트",
    ],
    curriculum: [
      "블로그 수익화의 큰 그림",
      "네이버 블로그와 티스토리 비교",
      "워드프레스가 필요한 경우",
      "첫 10개 글 주제 잡는 방법",
    ],
    formats: ["PDF 22p", "플랫폼 비교표", "키워드 예시"],
    outcomes: [
      "나에게 맞는 블로그 플랫폼을 선택하는 기준을 세울 수 있습니다.",
      "글이 수익으로 연결되는 흐름을 구조적으로 이해합니다.",
    ],
    caution: "검색 기반 콘텐츠는 누적 시간이 필요합니다. 단기간 결과보다 방향 검증에 초점을 맞추는 것이 좋습니다.",
    relatedSlugs: ["naver-blog-seo", "tistory-adsense"],
  },
  {
    slug: "naver-blog-seo",
    title: "네이버 블로그 검색 SEO 입문",
    category: "검색 SEO",
    group: "seo-blog",
    summary: "네이버 블로그에서 검색 유입을 만드는 키워드 선정과 글 구성 방법을 정리합니다.",
    target: "검색 유입으로 블로그를 키우고 싶은 분",
    level: "기초",
    duration: "45분",
    minutes: 45,
    price: "19,000원",
    priceNumber: 19000,
    tags: ["SEO", "블로그", "검색형"],
    thumbnail: "/course-thumbnails/youtube-revenue.webp",
    materialPdf: "/course-materials/blog-monetization.pdf",
    badge: "추천",
    cardCategory: "네이버 SEO",
    originalPrice: "44,000원",
    rating: 4.7,
    reviewCount: 402,
    intro: "네이버 블로그에서 검색 유입을 만드는 키워드 선정과 글 구성 방법을, 초보자 눈높이로 정리한 강의입니다.",
    recommendedFor: [
      "검색 유입으로 블로그를 키우고 싶은 분",
      "키워드를 어떻게 골라야 할지 막막한 분",
      "글을 써도 노출이 안 되는 분",
    ],
    learnings: [
      "검색 키워드 발굴과 선정 기준",
      "노출에 유리한 글 구성",
      "꾸준히 운영하는 발행 루틴",
    ],
    curriculum: [
      "네이버 검색 노출의 기본 원리",
      "키워드 발굴과 선정",
      "검색에 맞는 글 구성",
      "발행 루틴과 점검",
    ],
    formats: ["PDF 18p", "키워드 예시", "글 구성 템플릿"],
    outcomes: [
      "검색 유입을 위한 키워드 선택 기준을 세울 수 있습니다.",
      "노출에 유리한 글 구조를 잡을 수 있습니다.",
    ],
    caution: "검색 노출은 누적 시간이 필요하고 정책이 바뀔 수 있습니다. 단기 결과보다 꾸준함이 중요합니다.",
    relatedSlugs: ["blog-monetization", "tistory-adsense"],
  },
  {
    slug: "tistory-adsense",
    title: "티스토리 애드센스 시작하기",
    category: "애드센스",
    group: "seo-blog",
    summary: "티스토리 블로그로 구글 애드센스 광고 수익 구조를 이해하고 시작 준비를 합니다.",
    target: "광고 수익형 블로그를 시작하려는 분",
    level: "기초",
    duration: "50분",
    minutes: 50,
    price: "20,000원",
    priceNumber: 20000,
    tags: ["애드센스", "블로그", "광고"],
    thumbnail: "/course-thumbnails/blog-monetization.webp",
    materialPdf: "/course-materials/blog-monetization.pdf",
    badge: "신규",
    cardCategory: "애드센스",
    originalPrice: "46,000원",
    rating: 4.6,
    reviewCount: 357,
    intro: "티스토리 블로그로 구글 애드센스 광고 수익 구조를 이해하고, 승인 준비와 운영 기준을 정리하는 강의입니다.",
    recommendedFor: [
      "광고 수익형 블로그를 시작하려는 분",
      "애드센스 승인 과정이 궁금한 분",
      "검색 글쓰기에 관심 있는 분",
    ],
    learnings: [
      "애드센스 광고 수익의 기본 구조",
      "승인을 위한 블로그 준비",
      "광고 배치와 운영 기준",
    ],
    curriculum: [
      "애드센스 수익 구조 이해",
      "티스토리 블로그 준비",
      "승인 신청과 점검",
      "광고 배치와 정책 준수",
    ],
    formats: ["PDF 18p", "승인 체크리스트", "예시 이미지"],
    outcomes: [
      "애드센스 수익이 만들어지는 구조를 이해합니다.",
      "승인 준비에 필요한 항목을 점검할 수 있습니다.",
    ],
    caution: "애드센스는 정책이 엄격하고 승인·수익에 시간이 걸립니다. 정책 준수가 가장 중요합니다.",
    relatedSlugs: ["blog-monetization", "naver-blog-seo"],
  },
  {
    slug: "ecommerce-basic",
    title: "이커머스 시작 전 구조 이해",
    category: "이커머스 입문",
    group: "ecommerce",
    summary: "상품 선정, 마진, CS, 물류 흐름을 초보자 눈높이로 정리합니다.",
    target: "판매와 운영형 부업이 궁금한 분",
    level: "기초",
    duration: "60분",
    minutes: 60,
    price: "24,000원",
    priceNumber: 24000,
    tags: ["실전형", "판매형", "추천"],
    thumbnail: "/course-thumbnails/ecommerce-basic.webp",
    materialPdf: "/course-materials/ecommerce-basic.pdf",
    badge: "베스트셀러",
    cardCategory: "이커머스",
    originalPrice: "69,000원",
    rating: 4.9,
    reviewCount: 1842,
    intro: "온라인 판매를 시작하기 전 상품과 운영, 비용 구조를 먼저 이해하도록 돕는 강의입니다.",
    recommendedFor: [
      "스마트스토어, 오픈마켓 판매가 궁금한 분",
      "위탁판매와 사입의 차이를 알고 싶은 분",
      "마진 계산과 운영 부담을 먼저 확인하고 싶은 분",
    ],
    learnings: [
      "온라인 판매의 비용과 마진 구조",
      "위탁판매, 사입, 자체 제작의 차이",
      "상품 페이지와 CS의 기본 역할",
      "초보자가 확인해야 할 리스크",
    ],
    curriculum: [
      "이커머스 수익 구조 한눈에 보기",
      "상품 소싱 방식 비교",
      "마진 계산 예시",
      "첫 상품 검증 체크리스트",
    ],
    formats: ["PDF 24p", "마진 계산표", "운영 체크리스트"],
    outcomes: [
      "판매형 부업의 실제 업무 흐름을 이해할 수 있습니다.",
      "시작 전 필요한 비용과 운영 부담을 현실적으로 가늠할 수 있습니다.",
    ],
    caution: "판매형 모델은 재고, 환불, 고객 응대가 함께 따라옵니다. 구조를 이해한 뒤 작게 검증하는 것을 권장합니다.",
    relatedSlugs: ["consignment-sales", "product-sourcing"],
  },
  {
    slug: "consignment-sales",
    title: "위탁판매 입문 가이드",
    category: "위탁판매",
    group: "ecommerce",
    summary: "재고 부담 없이 시작하는 위탁판매의 구조와 상품 등록, 운영 흐름을 정리합니다.",
    target: "재고 없이 온라인 판매를 시작하려는 분",
    level: "입문",
    duration: "40분",
    minutes: 40,
    price: "18,000원",
    priceNumber: 18000,
    tags: ["입문자용", "위탁판매", "판매형"],
    thumbnail: "/course-thumbnails/ecommerce-basic.webp",
    materialPdf: "/course-materials/ecommerce-basic.pdf",
    badge: "입문추천",
    cardCategory: "위탁판매",
    originalPrice: "42,000원",
    rating: 4.7,
    reviewCount: 298,
    intro: "재고 부담 없이 시작할 수 있는 위탁판매의 구조와 상품 등록, 주문·CS 흐름을 정리한 입문 강의입니다.",
    recommendedFor: [
      "재고 없이 온라인 판매를 시작하려는 분",
      "위탁판매와 사입의 차이가 궁금한 분",
      "작게 판매를 검증하고 싶은 분",
    ],
    learnings: [
      "위탁판매의 기본 구조와 마진",
      "상품 등록과 주문 처리 흐름",
      "CS와 반품에서 주의할 점",
    ],
    curriculum: [
      "위탁판매 수익 구조 한눈에 보기",
      "상품 소싱과 등록",
      "주문과 배송 흐름",
      "CS와 리스크 관리",
    ],
    formats: ["PDF 16p", "운영 체크리스트", "마진 계산 예시"],
    outcomes: [
      "위탁판매의 업무 흐름을 이해합니다.",
      "시작 전 마진과 운영 부담을 가늠할 수 있습니다.",
    ],
    caution: "위탁판매도 CS와 반품 대응이 따라옵니다. 마진이 낮을 수 있어 구조를 먼저 이해하는 것이 중요합니다.",
    relatedSlugs: ["ecommerce-basic", "product-sourcing"],
  },
  {
    slug: "product-sourcing",
    title: "온라인 상품 소싱 기초",
    category: "상품 소싱",
    group: "ecommerce",
    summary: "팔리는 상품을 찾는 소싱 채널과 마진을 판단하는 기본 기준을 배웁니다.",
    target: "판매할 상품 선택이 막막한 분",
    level: "기초",
    duration: "45분",
    minutes: 45,
    price: "21,000원",
    priceNumber: 21000,
    tags: ["소싱", "판매형", "실전형"],
    thumbnail: "/course-thumbnails/agency-sidejob.webp",
    materialPdf: "/course-materials/ecommerce-basic.pdf",
    badge: "추천",
    cardCategory: "상품 소싱",
    originalPrice: "48,000원",
    rating: 4.8,
    reviewCount: 264,
    intro: "팔리는 상품을 찾는 소싱 채널과 마진을 판단하는 기준을 정리해, 상품 선택의 막막함을 줄여 주는 강의입니다.",
    recommendedFor: [
      "판매할 상품 선택이 막막한 분",
      "소싱 채널을 비교하고 싶은 분",
      "마진 계산 기준이 필요한 분",
    ],
    learnings: [
      "대표 소싱 채널의 특징 비교",
      "수요와 경쟁을 확인하는 방법",
      "마진과 비용을 판단하는 기준",
    ],
    curriculum: [
      "상품 소싱의 기본 흐름",
      "소싱 채널 비교",
      "수요·경쟁 확인하기",
      "마진 계산과 검증",
    ],
    formats: ["PDF 18p", "소싱 채널 비교표", "마진 계산표"],
    outcomes: [
      "상품을 고르는 기본 기준을 세울 수 있습니다.",
      "마진과 비용을 미리 계산해 볼 수 있습니다.",
    ],
    caution: "잘 팔리는 상품도 경쟁과 비용에 따라 마진이 달라집니다. 작게 검증한 뒤 확대하는 것이 안전합니다.",
    relatedSlugs: ["ecommerce-basic", "consignment-sales"],
  },
];

export type Notice = {
  title: string;
  date: string;
  summary: string;
  content: string[];
};

export const notices: Notice[] = [
  {
    title: "캐쉬움 베타 서비스 안내",
    date: "2026.05.13",
    summary: "추천 설문과 핵심 구조형 강의 페이지를 먼저 제공합니다.",
    content: [
      "캐쉬움 베타 서비스가 시작되었습니다. 이번 베타에서는 수익 구조 이해를 돕는 핵심 강의와 추천 설문을 우선 공개합니다.",
      "추천 설문은 6개의 질문을 통해 리뷰어, AI 활용기반 서비스 제작, 제휴 마케팅, SEO & 블로그 수익화, 이커머스 중 어떤 방향을 먼저 살펴보면 좋을지 좁혀줍니다. 설문 결과는 수익을 보장하지 않으며, 학습의 출발점을 안내하는 용도입니다.",
      "베타 기간 동안 일부 강의와 결제 흐름은 점진적으로 추가됩니다. 이용 중 불편한 점이나 개선 의견이 있다면 문의 채널로 알려주시면 운영에 반영하겠습니다.",
    ],
  },
  {
    title: "강의 자료 업데이트 기준 안내",
    date: "2026.05.10",
    summary: "플랫폼 정책이나 시장 변화가 큰 주제는 자료를 주기적으로 점검합니다.",
    content: [
      "캐쉬움의 강의 자료는 시장 상황과 플랫폼 정책 변화를 반영해 주기적으로 점검합니다.",
      "특히 AI 도구, 블로그, 이커머스처럼 정책 변화가 잦은 주제는 분기마다 핵심 내용을 다시 검토하고, 변경 사항이 크면 자료를 개정합니다.",
      "이미 수강 중인 강의의 자료가 개정되면 마이페이지에서 최신 버전으로 다시 확인할 수 있습니다. 개정 이력은 각 강의 페이지에서 함께 안내됩니다.",
    ],
  },
  {
    title: "문의 채널 운영 시간 안내",
    date: "2026.05.01",
    summary: "평일 오전 10시부터 오후 6시까지 접수된 문의를 순차적으로 확인합니다.",
    content: [
      "문의 채널은 평일 오전 10시부터 오후 6시까지 운영합니다. 주말과 공휴일에 접수된 문의는 다음 영업일에 순차적으로 확인합니다.",
      "결제, 환불, 자료 열람 관련 문의는 가입하신 이메일과 함께 남겨주시면 더 빠르게 확인할 수 있습니다.",
      "운영 시간 외에도 문의 접수는 언제든 가능하며, 접수 순서대로 답변을 드립니다. 답변은 보통 1영업일 이내에 안내됩니다.",
    ],
  },
];

export function getCourse(slug: string) {
  return courses.find((course) => course.slug === slug);
}

export function getRelatedCourses(slugs: string[]) {
  return slugs.map((slug) => getCourse(slug)).filter((course): course is Course => Boolean(course));
}
